# Generated by Django 2.1.7 on 2019-03-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('access_token', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(max_length=25, unique=True)),
                ('profile_picture_url', models.CharField(blank=True, max_length=2100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=200)),
                ('api_key', models.CharField(max_length=200, unique=True)),
                ('api_key_secret', models.CharField(max_length=200)),
                ('callback_url', models.CharField(blank=True, max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.CharField(max_length=25)),
                ('to_user_id', models.CharField(max_length=25)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TwitterTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user_id', models.CharField(max_length=25)),
                ('to_user_id', models.CharField(max_length=25)),
                ('contents', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='twitteraccount',
            name='twitter_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.TwitterApp'),
        ),
    ]
